# Generated by Django 4.2 on 2023-04-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileCounter', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('groupName', models.CharField(max_length=50)),
                ('uploader', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=10000)),
                ('encryptedKey', models.CharField(max_length=10000)),
                ('iv', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
                ('publicKey', models.CharField(max_length=10000)),
                ('privateKey', models.CharField(max_length=10000)),
                ('manager', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('groupName', models.CharField(max_length=50)),
                ('manager', models.BooleanField()),
            ],
        ),
    ]
